const members = [
    {
        fullName: "Tal Friedman",
        email: "tal.friedman@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/0.jpg",
        location: {
            country: "Israel",
            state: "Jerusalem District",
            city: "Ma'ale Adumim",
        },
        phone: "+972-56-855-3504",
        linkedinURL: "https://linkedin.com/in/talfriedman",
        facebookURL: "https://facebook.com/tal.friedman",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Volunteers with youth coding bootcamps.",
        jobs_history: [
            {
                role: "Intern",
                companyName: "CodeBase",
                startDate: "2014-10-09",
                endDate: "Present",
            },
            {
                role: "Project Manager",
                companyName: "GreenWave",
                startDate: "2018-10-13",
                endDate: "2018-12-12",
            },
        ],
        years_of_experience: 15,
        groups: ["Operations", "Product Management", "QA / Testing"],
    },
    {
        fullName: "Asaf Gross",
        email: "asaf.gross@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/1.jpg",
        location: {
            country: "Israel",
            state: "Jerusalem District",
            city: "Jerusalem",
        },
        phone: "+972-50-511-6509",
        linkedinURL: "https://linkedin.com/in/asafgross",
        facebookURL: "https://facebook.com/asaf.gross",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Committed to improving software accessibility.",
        jobs_history: [
            {
                role: "Product Manager",
                companyName: "EcoSoft",
                startDate: "2012-11-01",
                endDate: "Present",
            },
            {
                role: "Marketing Coordinator",
                companyName: "Alpha Solutions",
                startDate: "2020-10-02",
                endDate: "2021-01-14",
            },
        ],
        years_of_experience: 1,
        groups: ["Legal", "Engineering", "QA / Testing", "IT", "Security"],
    },
    {
        fullName: "Asaf Shamir",
        email: "asaf.shamir@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/2.jpg",
        location: {
            country: "Israel",
            state: "Tel Aviv District",
            city: "Givatayim",
        },
        phone: "+972-51-536-5735",
        linkedinURL: "https://linkedin.com/in/asafshamir",
        facebookURL: "https://facebook.com/asaf.shamir",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Interested in AI and machine learning advancements.",
        jobs_history: [
            {
                role: "Fullstack Engineer",
                companyName: "GreenWave",
                startDate: "2010-07-19",
                endDate: "2010-07-05",
            },
            {
                role: "Marketing Coordinator",
                companyName: "BrightMind",
                startDate: "2012-04-26",
                endDate: "2020-05-14",
            },
        ],
        years_of_experience: 7,
        groups: [
            "Human Resources",
            "Sales",
            "Operations",
            "Logistics",
            "Administration",
        ],
    },
    {
        fullName: "Erez Shamir",
        email: "erez.shamir@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/3.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Nazareth",
        },
        phone: "+972-55-688-8989",
        linkedinURL: "https://linkedin.com/in/erezshamir",
        facebookURL: "https://facebook.com/erez.shamir",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Volunteers with youth coding bootcamps.",
        jobs_history: [
            {
                role: "Data Analyst",
                companyName: "BrightMind",
                startDate: "2010-01-15",
                endDate: "Present",
            },
            {
                role: "Security Analyst",
                companyName: "Techly",
                startDate: "2015-08-17",
                endDate: "2017-10-19",
            },
        ],
        years_of_experience: 13,
        groups: ["Public Relations", "Training"],
    },
    {
        fullName: "Shira Regev",
        email: "shira.regev@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/4.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Nesher",
        },
        phone: "+972-53-170-4426",
        linkedinURL: "https://linkedin.com/in/shiraregev",
        facebookURL: "https://facebook.com/shira.regev",
        wantsUpdates: true,
        gender: "Female",
        additionalInfo: "Specializes in mobile app development.",
        jobs_history: [
            {
                role: "Data Analyst",
                companyName: "CodeBase",
                startDate: "2010-10-27",
                endDate: "2011-12-12",
            },
            {
                role: "Sales Manager",
                companyName: "SoftWorks",
                startDate: "2012-11-02",
                endDate: "2015-09-08",
            },
        ],
        years_of_experience: 13,
        groups: ["Security", "Finance", "IT", "Marketing"],
    },
    {
        fullName: "Adi Cohen",
        email: "adi.cohen@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/5.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Nazareth",
        },
        phone: "+972-59-472-1643",
        linkedinURL: "https://linkedin.com/in/adicohen",
        facebookURL: "https://facebook.com/adi.cohen",
        wantsUpdates: true,
        gender: "Non-binary",
        additionalInfo: "Active in tech meetups and open source.",
        jobs_history: [
            {
                role: "Customer Success Manager",
                companyName: "MarketSense",
                startDate: "2010-05-25",
                endDate: "Present",
            },
            {
                role: "DevOps Engineer",
                companyName: "NextGen",
                startDate: "2011-11-17",
                endDate: "2020-10-21",
            },
        ],
        years_of_experience: 11,
        groups: ["Engineering", "Administration", "Finance", "UX Research"],
    },
    {
        fullName: "Boaz Friedman",
        email: "boaz.friedman@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/7.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Kiryat Shmona",
        },
        phone: "+972-58-484-2055",
        linkedinURL: "https://linkedin.com/in/boazfriedman",
        facebookURL: "https://facebook.com/boaz.friedman",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Volunteers with youth coding bootcamps.",
        jobs_history: [
            {
                role: "Sales Manager",
                companyName: "QuantumSoft",
                startDate: "2019-09-21",
                endDate: "Present",
            },
        ],
        years_of_experience: 10,
        groups: ["Training", "Sales", "Finance"],
    },
    {
        fullName: "Michal Gross",
        email: "michal.gross@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/8.jpg",
        location: {
            country: "Israel",
            state: "Southern District",
            city: "Eilat",
        },
        phone: "+972-57-842-9020",
        linkedinURL: "https://linkedin.com/in/michalgross",
        facebookURL: "https://facebook.com/michal.gross",
        wantsUpdates: true,
        gender: "Non-binary",
        additionalInfo: "Interested in AI and machine learning advancements.",
        jobs_history: [
            {
                role: "Product Manager",
                companyName: "InnoTech",
                startDate: "2010-10-02",
                endDate: "2015-09-01",
            },
        ],
        years_of_experience: 4,
        groups: [
            "Public Relations",
            "Training",
            "Customer Success",
            "Product Management",
            "Security",
        ],
    },
    {
        fullName: "Yarden Shamir",
        email: "yarden.shamir@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/9.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Nesher",
        },
        phone: "+972-50-985-6913",
        linkedinURL: "https://linkedin.com/in/yardenshamir",
        facebookURL: "https://facebook.com/yarden.shamir",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Specializes in mobile app development.",
        jobs_history: [
            {
                role: "Fullstack Engineer",
                companyName: "NextGen",
                startDate: "2010-07-26",
                endDate: "Present",
            },
            {
                role: "Data Scientist",
                companyName: "NextGen",
                startDate: "2012-12-08",
                endDate: "2016-09-05",
            },
        ],
        years_of_experience: 6,
        groups: ["Engineering", "Sales", "Security", "Legal"],
    },
    {
        fullName: "Adi Barak",
        email: "adi.barak@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/10.jpg",
        location: {
            country: "Israel",
            state: "Tel Aviv District",
            city: "Tel Aviv",
        },
        phone: "+972-57-359-8543",
        linkedinURL: "https://linkedin.com/in/adibarak",
        facebookURL: "https://facebook.com/adi.barak",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Interested in AI and machine learning advancements.",
        jobs_history: [
            {
                role: "UX Designer",
                companyName: "InsightData",
                startDate: "2012-01-21",
                endDate: "Present",
            },
            {
                role: "QA Engineer",
                companyName: "WebCore",
                startDate: "2013-11-01",
                endDate: "2015-06-07",
            },
        ],
        years_of_experience: 14,
        groups: [
            "QA / Testing",
            "Public Relations",
            "Customer Success",
            "Engineering",
            "Security",
        ],
    },
    {
        fullName: "Noam Cohen",
        email: "noam.cohen@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/11.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Acre",
        },
        phone: "+972-55-319-1930",
        linkedinURL: "https://linkedin.com/in/noamcohen",
        facebookURL: "https://facebook.com/noam.cohen",
        wantsUpdates: true,
        gender: "Non-binary",
        additionalInfo: "Passionate about user research and accessibility.",
        jobs_history: [
            {
                role: "Backend Developer",
                companyName: "InsightData",
                startDate: "2010-05-23",
                endDate: "Present",
            },
            {
                role: "Marketing Coordinator",
                companyName: "Vibrant Tech",
                startDate: "2011-01-12",
                endDate: "2022-05-04",
            },
        ],
        years_of_experience: 1,
        groups: ["Logistics", "Engineering"],
    },
    {
        fullName: "Orly Tal",
        email: "orly.tal@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/12.jpg",
        location: {
            country: "Israel",
            state: "Tel Aviv District",
            city: "Tel Aviv",
        },
        phone: "+972-56-310-9585",
        linkedinURL: "https://linkedin.com/in/orlytal",
        facebookURL: "https://facebook.com/orly.tal",
        wantsUpdates: false,
        gender: "Female",
        additionalInfo:
            "Fan of agile methodologies and continuous improvement.",
        jobs_history: [
            {
                role: "Product Manager",
                companyName: "GreenWave",
                startDate: "2010-12-19",
                endDate: "Present",
            },
        ],
        years_of_experience: 12,
        groups: [
            "Product Management",
            "Operations",
            "Human Resources",
            "Security",
            "Finance",
        ],
    },
    {
        fullName: "Tal Cohen",
        email: "tal.cohen@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/13.jpg",
        location: {
            country: "Israel",
            state: "Southern District",
            city: "Beersheba",
        },
        phone: "+972-52-412-6844",
        linkedinURL: "https://linkedin.com/in/talcohen",
        facebookURL: "https://facebook.com/tal.cohen",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Speaks at community events regularly.",
        jobs_history: [
            {
                role: "Security Analyst",
                companyName: "MarketSense",
                startDate: "2010-06-12",
                endDate: "Present",
            },
            {
                role: "Marketing Coordinator",
                companyName: "StartupLabs",
                startDate: "2014-08-12",
                endDate: "2016-03-05",
            },
        ],
        years_of_experience: 13,
        groups: ["Training", "Finance", "Product Management"],
    },
    {
        fullName: "Noam Gross",
        email: "noam.gross@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/14.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Haifa",
        },
        phone: "+972-58-935-4261",
        linkedinURL: "https://linkedin.com/in/noamgross",
        facebookURL: "https://facebook.com/noam.gross",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Passionate about user research and accessibility.",
        jobs_history: [
            {
                role: "Data Analyst",
                companyName: "SoftWorks",
                startDate: "2010-09-06",
                endDate: "Present",
            },
        ],
        years_of_experience: 6,
        groups: ["Product Management", "Training"],
    },
    {
        fullName: "Tal Elbaz",
        email: "tal.elbaz@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/15.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Safed",
        },
        phone: "+972-54-284-5668",
        linkedinURL: "https://linkedin.com/in/talelbaz",
        facebookURL: "https://facebook.com/tal.elbaz",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Interested in AI and machine learning advancements.",
        jobs_history: [
            {
                role: "Data Analyst",
                companyName: "WebCore",
                startDate: "2010-06-17",
                endDate: "2010-01-26",
            },
            {
                role: "Fullstack Engineer",
                companyName: "GreenWave",
                startDate: "2014-02-06",
                endDate: "2015-05-09",
            },
        ],
        years_of_experience: 4,
        groups: ["Product Management", "Human Resources"],
    },
    {
        fullName: "Orly Oren",
        email: "orly.oren@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/16.jpg",
        location: {
            country: "Israel",
            state: "Central District",
            city: "Netanya",
        },
        phone: "+972-53-179-6786",
        linkedinURL: "https://linkedin.com/in/orlyoren",
        facebookURL: "https://facebook.com/orly.oren",
        wantsUpdates: false,
        gender: "Female",
        additionalInfo: "Enjoys working on backend microservices.",
        jobs_history: [
            {
                role: "Backend Developer",
                companyName: "WebCore",
                startDate: "2010-06-22",
                endDate: "2010-09-17",
            },
            {
                role: "Data Scientist",
                companyName: "Microserve",
                startDate: "2013-03-07",
                endDate: "2013-10-18",
            },
        ],
        years_of_experience: 5,
        groups: [
            "Administration",
            "Customer Success",
            "Legal",
            "Support",
            "Public Relations",
        ],
    },
    {
        fullName: "Nava Oren",
        email: "nava.oren@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/17.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Nazareth",
        },
        phone: "+972-54-439-9890",
        linkedinURL: "https://linkedin.com/in/navaoren",
        facebookURL: "https://facebook.com/nava.oren",
        wantsUpdates: true,
        gender: "Female",
        additionalInfo: "Experienced in cloud infrastructure and DevOps.",
        jobs_history: [
            {
                role: "Data Analyst",
                companyName: "DataStream",
                startDate: "2015-04-11",
                endDate: "Present",
            },
        ],
        years_of_experience: 5,
        groups: ["Training", "Product Management"],
    },
    {
        fullName: "Dafna Shalev",
        email: "dafna.shalev@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/18.jpg",
        location: {
            country: "Israel",
            state: "Tel Aviv District",
            city: "Ramat Gan",
        },
        phone: "+972-50-830-8357",
        linkedinURL: "https://linkedin.com/in/dafnashalev",
        facebookURL: "https://facebook.com/dafna.shalev",
        wantsUpdates: false,
        gender: "Female",
        additionalInfo: "Interested in sustainable tech solutions.",
        jobs_history: [
            {
                role: "DevOps Engineer",
                companyName: "Vibrant Tech",
                startDate: "2010-06-09",
                endDate: "2011-08-23",
            },
            {
                role: "Data Analyst",
                companyName: "StartupLabs",
                startDate: "2012-08-10",
                endDate: "2019-12-28",
            },
        ],
        years_of_experience: 6,
        groups: ["Security", "Business Development", "Sales"],
    },
    {
        fullName: "Tamar Elbaz",
        email: "tamar.elbaz@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/19.jpg",
        location: {
            country: "Israel",
            state: "Jerusalem District",
            city: "Jerusalem",
        },
        phone: "+972-53-326-6616",
        linkedinURL: "https://linkedin.com/in/tamarelbaz",
        facebookURL: "https://facebook.com/tamar.elbaz",
        wantsUpdates: true,
        gender: "Female",
        additionalInfo: "Focuses on cybersecurity and data privacy.",
        jobs_history: [
            {
                role: "Business Analyst",
                companyName: "InsightData",
                startDate: "2010-05-07",
                endDate: "2013-11-12",
            },
            {
                role: "Data Scientist",
                companyName: "DataStream",
                startDate: "2018-08-08",
                endDate: "2024-05-17",
            },
        ],
        years_of_experience: 7,
        groups: [
            "Training",
            "Customer Success",
            "Finance",
            "Operations",
            "Human Resources",
        ],
    },
    {
        fullName: "Hila Regev",
        email: "hila.regev@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/20.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Safed",
        },
        phone: "+972-54-432-5653",
        linkedinURL: "https://linkedin.com/in/hilaregev",
        facebookURL: "https://facebook.com/hila.regev",
        wantsUpdates: true,
        gender: "Non-binary",
        additionalInfo: "Committed to improving software accessibility.",
        jobs_history: [
            {
                role: "Project Manager",
                companyName: "BrightMind",
                startDate: "2010-04-09",
                endDate: "Present",
            },
            {
                role: "Support Specialist",
                companyName: "Vibrant Tech",
                startDate: "2012-09-03",
                endDate: "2015-11-15",
            },
            {
                role: "QA Engineer",
                companyName: "DataStream",
                startDate: "2020-04-26",
                endDate: "2024-02-04",
            },
        ],
        years_of_experience: 5,
        groups: ["Marketing", "Human Resources"],
    },
    {
        fullName: "Maya Katz",
        email: "maya.katz@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/21.jpg",
        location: {
            country: "Israel",
            state: "Central District",
            city: "Rehovot",
        },
        phone: "+972-51-954-3233",
        linkedinURL: "https://linkedin.com/in/mayakatz",
        facebookURL: "https://facebook.com/maya.katz",
        wantsUpdates: true,
        gender: "Female",
        additionalInfo: "Loves mentoring new developers.",
        jobs_history: [
            {
                role: "Business Analyst",
                companyName: "StartupLabs",
                startDate: "2015-08-23",
                endDate: "Present",
            },
        ],
        years_of_experience: 12,
        groups: ["Customer Success", "Operations", "Legal", "Finance"],
    },
    {
        fullName: "Eitan Barak",
        email: "eitan.barak@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/22.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Nazareth",
        },
        phone: "+972-51-144-7113",
        linkedinURL: "https://linkedin.com/in/eitanbarak",
        facebookURL: "https://facebook.com/eitan.barak",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Committed to improving software accessibility.",
        jobs_history: [
            {
                role: "Business Analyst",
                companyName: "Microserve",
                startDate: "2010-02-05",
                endDate: "2010-03-25",
            },
        ],
        years_of_experience: 9,
        groups: [
            "Security",
            "Human Resources",
            "UX Research",
            "Operations",
            "Business Development",
        ],
    },
    {
        fullName: "Daniel Shalev",
        email: "daniel.shalev@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/23.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Kiryat Shmona",
        },
        phone: "+972-51-971-9488",
        linkedinURL: "https://linkedin.com/in/danielshalev",
        facebookURL: "https://facebook.com/daniel.shalev",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Speaks at community events regularly.",
        jobs_history: [
            {
                role: "Data Analyst",
                companyName: "WebCore",
                startDate: "2010-05-23",
                endDate: "2023-09-02",
            },
        ],
        years_of_experience: 5,
        groups: ["Administration", "Sales", "Marketing", "Training", "Support"],
    },
    {
        fullName: "Yonatan Oren",
        email: "yonatan.oren@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/24.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Acre",
        },
        phone: "+972-52-606-1320",
        linkedinURL: "https://linkedin.com/in/yonatanoren",
        facebookURL: "https://facebook.com/yonatan.oren",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Loves mentoring new developers.",
        jobs_history: [
            {
                role: "UX Designer",
                companyName: "NextGen",
                startDate: "2016-06-22",
                endDate: "Present",
            },
        ],
        years_of_experience: 9,
        groups: [
            "Administration",
            "Security",
            "Support",
            "Public Relations",
            "IT",
        ],
    },
    {
        fullName: "Asaf Tal",
        email: "asaf.tal@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/25.jpg",
        location: {
            country: "Israel",
            state: "Central District",
            city: "Rehovot",
        },
        phone: "+972-51-460-1924",
        linkedinURL: "https://linkedin.com/in/asaftal",
        facebookURL: "https://facebook.com/asaf.tal",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Enjoys working on backend microservices.",
        jobs_history: [
            {
                role: "Project Manager",
                companyName: "Skyline",
                startDate: "2010-09-02",
                endDate: "Present",
            },
            {
                role: "Product Manager",
                companyName: "Designify",
                startDate: "2017-11-01",
                endDate: "2021-05-15",
            },
        ],
        years_of_experience: 5,
        groups: [
            "Legal",
            "Business Development",
            "Customer Success",
            "Human Resources",
        ],
    },
    {
        fullName: "Itai Mizrahi",
        email: "itai.mizrahi@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/26.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Kiryat Shmona",
        },
        phone: "+972-58-330-3741",
        linkedinURL: "https://linkedin.com/in/itaimizrahi",
        facebookURL: "https://facebook.com/itai.mizrahi",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Focuses on cybersecurity and data privacy.",
        jobs_history: [
            {
                role: "Customer Success Manager",
                companyName: "InsightData",
                startDate: "2010-11-27",
                endDate: "Present",
            },
        ],
        years_of_experience: 6,
        groups: [
            "Legal",
            "Training",
            "IT",
            "Customer Success",
            "Product Management",
        ],
    },
    {
        fullName: "Noam Shalev",
        email: "noam.shalev@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/27.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Haifa",
        },
        phone: "+972-51-233-8478",
        linkedinURL: "https://linkedin.com/in/noamshalev",
        facebookURL: "https://facebook.com/noam.shalev",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Committed to improving software accessibility.",
        jobs_history: [
            {
                role: "Frontend Developer",
                companyName: "CodeBase",
                startDate: "2010-02-10",
                endDate: "Present",
            },
            {
                role: "Business Analyst",
                companyName: "BlueOcean",
                startDate: "2015-06-13",
                endDate: "2023-08-18",
            },
        ],
        years_of_experience: 10,
        groups: ["Operations", "IT", "Product Management"],
    },
    {
        fullName: "Itai Levi",
        email: "itai.levi@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/28.jpg",
        location: {
            country: "Israel",
            state: "Tel Aviv District",
            city: "Ramat Gan",
        },
        phone: "+972-57-552-7464",
        linkedinURL: "https://linkedin.com/in/itailevi",
        facebookURL: "https://facebook.com/itai.levi",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo:
            "Fan of agile methodologies and continuous improvement.",
        jobs_history: [
            {
                role: "Support Specialist",
                companyName: "GreenWave",
                startDate: "2010-10-28",
                endDate: "Present",
            },
        ],
        years_of_experience: 14,
        groups: [
            "Human Resources",
            "Public Relations",
            "Sales",
            "Customer Success",
            "Engineering",
        ],
    },
    {
        fullName: "Maya Navon",
        email: "maya.navon@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/29.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Kiryat Shmona",
        },
        phone: "+972-56-528-4459",
        linkedinURL: "https://linkedin.com/in/mayanavon",
        facebookURL: "https://facebook.com/maya.navon",
        wantsUpdates: false,
        gender: "Female",
        additionalInfo: "Interested in sustainable tech solutions.",
        jobs_history: [
            {
                role: "Intern",
                companyName: "GreenWave",
                startDate: "2010-04-14",
                endDate: "Present",
            },
            {
                role: "QA Engineer",
                companyName: "EcoSoft",
                startDate: "2011-06-01",
                endDate: "2011-01-02",
            },
            {
                role: "Product Manager",
                companyName: "BrightMind",
                startDate: "2012-03-28",
                endDate: "2016-07-23",
            },
        ],
        years_of_experience: 10,
        groups: ["Product Management", "Engineering"],
    },
    {
        fullName: "Gal Friedman",
        email: "gal.friedman@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/30.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Kiryat Shmona",
        },
        phone: "+972-54-340-1552",
        linkedinURL: "https://linkedin.com/in/galfriedman",
        facebookURL: "https://facebook.com/gal.friedman",
        wantsUpdates: true,
        gender: "Female",
        additionalInfo: "Interested in sustainable tech solutions.",
        jobs_history: [
            {
                role: "Data Scientist",
                companyName: "MarketSense",
                startDate: "2012-11-04",
                endDate: "Present",
            },
            {
                role: "Intern",
                companyName: "Vibrant Tech",
                startDate: "2013-11-28",
                endDate: "2017-09-08",
            },
        ],
        years_of_experience: 10,
        groups: ["Support", "Engineering", "Finance"],
    },
    {
        fullName: "Shai Regev",
        email: "shai.regev@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/31.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Acre",
        },
        phone: "+972-57-865-1791",
        linkedinURL: "https://linkedin.com/in/shairegev",
        facebookURL: "https://facebook.com/shai.regev",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Specializes in mobile app development.",
        jobs_history: [
            {
                role: "HR Specialist",
                companyName: "WebCore",
                startDate: "2010-02-28",
                endDate: "2021-12-27",
            },
        ],
        years_of_experience: 4,
        groups: ["Marketing", "Legal", "Public Relations", "Support"],
    },
    {
        fullName: "Tomer Peretz",
        email: "tomer.peretz@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/32.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Nazareth",
        },
        phone: "+972-58-222-8079",
        linkedinURL: "https://linkedin.com/in/tomerperetz",
        facebookURL: "https://facebook.com/tomer.peretz",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Enjoys writing technical blogs and tutorials.",
        jobs_history: [
            {
                role: "UX Designer",
                companyName: "DataStream",
                startDate: "2011-10-13",
                endDate: "Present",
            },
        ],
        years_of_experience: 9,
        groups: [
            "UX Research",
            "Human Resources",
            "Sales",
            "Finance",
            "Administration",
        ],
    },
    {
        fullName: "Hila Levi",
        email: "hila.levi@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/33.jpg",
        location: {
            country: "Israel",
            state: "Tel Aviv District",
            city: "Givatayim",
        },
        phone: "+972-51-367-8558",
        linkedinURL: "https://linkedin.com/in/hilalevi",
        facebookURL: "https://facebook.com/hila.levi",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Volunteers with youth coding bootcamps.",
        jobs_history: [
            {
                role: "UX Designer",
                companyName: "Alpha Solutions",
                startDate: "2015-12-10",
                endDate: "Present",
            },
        ],
        years_of_experience: 2,
        groups: ["Human Resources", "Legal"],
    },
    {
        fullName: "Daniel Mizrahi",
        email: "daniel.mizrahi@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/34.jpg",
        location: {
            country: "Israel",
            state: "Southern District",
            city: "Eilat",
        },
        phone: "+972-53-650-2555",
        linkedinURL: "https://linkedin.com/in/danielmizrahi",
        facebookURL: "https://facebook.com/daniel.mizrahi",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo:
            "Active participant in hackathons and coding competitions.",
        jobs_history: [
            {
                role: "Operations Manager",
                companyName: "SoftWorks",
                startDate: "2011-11-09",
                endDate: "Present",
            },
            {
                role: "Frontend Developer",
                companyName: "SoftWorks",
                startDate: "2021-07-14",
                endDate: "2023-01-20",
            },
        ],
        years_of_experience: 4,
        groups: ["Customer Success", "Public Relations"],
    },
    {
        fullName: "Nava Golan",
        email: "nava.golan@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/35.jpg",
        location: {
            country: "Israel",
            state: "Tel Aviv District",
            city: "Givatayim",
        },
        phone: "+972-54-957-2697",
        linkedinURL: "https://linkedin.com/in/navagolan",
        facebookURL: "https://facebook.com/nava.golan",
        wantsUpdates: false,
        gender: "Female",
        additionalInfo: "Active in tech meetups and open source.",
        jobs_history: [
            {
                role: "Sales Manager",
                companyName: "MarketSense",
                startDate: "2014-03-13",
                endDate: "Present",
            },
            {
                role: "Fullstack Engineer",
                companyName: "QuantumSoft",
                startDate: "2020-06-17",
                endDate: "2025-07-27",
            },
        ],
        years_of_experience: 14,
        groups: ["Administration", "IT", "Logistics", "Support", "Legal"],
    },
    {
        fullName: "Ran Katz",
        email: "ran.katz@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/36.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Acre",
        },
        phone: "+972-58-481-5386",
        linkedinURL: "https://linkedin.com/in/rankatz",
        facebookURL: "https://facebook.com/ran.katz",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Active in tech meetups and open source.",
        jobs_history: [
            {
                role: "Intern",
                companyName: "SoftWorks",
                startDate: "2010-09-06",
                endDate: "2015-11-09",
            },
        ],
        years_of_experience: 5,
        groups: ["Security", "Human Resources", "UX Research"],
    },
    {
        fullName: "Noam Peretz",
        email: "noam.peretz@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/37.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Nazareth",
        },
        phone: "+972-56-970-3717",
        linkedinURL: "https://linkedin.com/in/noamperetz",
        facebookURL: "https://facebook.com/noam.peretz",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Speaks at community events regularly.",
        jobs_history: [
            {
                role: "HR Specialist",
                companyName: "Alpha Solutions",
                startDate: "2010-07-10",
                endDate: "Present",
            },
        ],
        years_of_experience: 6,
        groups: [
            "Business Development",
            "Marketing",
            "Public Relations",
            "Human Resources",
            "Finance",
        ],
    },
    {
        fullName: "Ruth Regev",
        email: "ruth.regev@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/38.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Safed",
        },
        phone: "+972-58-890-9652",
        linkedinURL: "https://linkedin.com/in/ruthregev",
        facebookURL: "https://facebook.com/ruth.regev",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Focuses on cybersecurity and data privacy.",
        jobs_history: [
            {
                role: "Intern",
                companyName: "BlueOcean",
                startDate: "2015-04-17",
                endDate: "Present",
            },
        ],
        years_of_experience: 7,
        groups: ["Security", "Product Management", "Legal"],
    },
    {
        fullName: "Asaf Mizrahi",
        email: "asaf.mizrahi@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/39.jpg",
        location: {
            country: "Israel",
            state: "Jerusalem District",
            city: "Ma'ale Adumim",
        },
        phone: "+972-59-918-3145",
        linkedinURL: "https://linkedin.com/in/asafmizrahi",
        facebookURL: "https://facebook.com/asaf.mizrahi",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Specializes in mobile app development.",
        jobs_history: [
            {
                role: "Project Manager",
                companyName: "Techly",
                startDate: "2010-09-22",
                endDate: "Present",
            },
            {
                role: "HR Specialist",
                companyName: "InsightData",
                startDate: "2011-08-24",
                endDate: "2012-08-18",
            },
        ],
        years_of_experience: 12,
        groups: [
            "Operations",
            "Human Resources",
            "Customer Success",
            "Business Development",
            "Security",
        ],
    },
    {
        fullName: "Nadav Goldman",
        email: "nadav.goldman@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/40.jpg",
        location: {
            country: "Israel",
            state: "Jerusalem District",
            city: "Beit Shemesh",
        },
        phone: "+972-50-386-7810",
        linkedinURL: "https://linkedin.com/in/nadavgoldman",
        facebookURL: "https://facebook.com/nadav.goldman",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Volunteers with youth coding bootcamps.",
        jobs_history: [
            {
                role: "Fullstack Engineer",
                companyName: "InsightData",
                startDate: "2010-04-10",
                endDate: "2010-05-23",
            },
            {
                role: "Marketing Coordinator",
                companyName: "DataStream",
                startDate: "2014-06-09",
                endDate: "2015-10-10",
            },
        ],
        years_of_experience: 4,
        groups: [
            "Product Management",
            "Marketing",
            "Support",
            "IT",
            "UX Research",
        ],
    },
    {
        fullName: "Vered Azulay",
        email: "vered.azulay@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/41.jpg",
        location: {
            country: "Israel",
            state: "Jerusalem District",
            city: "Jerusalem",
        },
        phone: "+972-57-809-3505",
        linkedinURL: "https://linkedin.com/in/veredazulay",
        facebookURL: "https://facebook.com/vered.azulay",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Interested in AI and machine learning advancements.",
        jobs_history: [
            {
                role: "Operations Manager",
                companyName: "WebCore",
                startDate: "2010-04-18",
                endDate: "2010-10-28",
            },
            {
                role: "Sales Manager",
                companyName: "MarketSense",
                startDate: "2012-11-16",
                endDate: "2020-07-15",
            },
        ],
        years_of_experience: 1,
        groups: [
            "Product Management",
            "Logistics",
            "Marketing",
            "Engineering",
            "Sales",
        ],
    },
    {
        fullName: "Avigail Goldman",
        email: "avigail.goldman@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/42.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Haifa",
        },
        phone: "+972-58-519-2357",
        linkedinURL: "https://linkedin.com/in/avigailgoldman",
        facebookURL: "https://facebook.com/avigail.goldman",
        wantsUpdates: true,
        gender: "Non-binary",
        additionalInfo: "Enjoys writing technical blogs and tutorials.",
        jobs_history: [
            {
                role: "UX Designer",
                companyName: "BlueOcean",
                startDate: "2013-02-03",
                endDate: "Present",
            },
        ],
        years_of_experience: 8,
        groups: [
            "IT",
            "Operations",
            "Business Development",
            "Public Relations",
            "Logistics",
        ],
    },
    {
        fullName: "Gilad Friedman",
        email: "gilad.friedman@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/43.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Safed",
        },
        phone: "+972-50-120-6771",
        linkedinURL: "https://linkedin.com/in/giladfriedman",
        facebookURL: "https://facebook.com/gilad.friedman",
        wantsUpdates: true,
        gender: "Male",
        additionalInfo: "Specializes in mobile app development.",
        jobs_history: [
            {
                role: "Intern",
                companyName: "Vibrant Tech",
                startDate: "2011-01-01",
                endDate: "Present",
            },
        ],
        years_of_experience: 9,
        groups: [
            "Customer Success",
            "Business Development",
            "Product Management",
            "Support",
        ],
    },
    {
        fullName: "Yonatan Tal",
        email: "yonatan.tal@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/44.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Acre",
        },
        phone: "+972-54-946-8376",
        linkedinURL: "https://linkedin.com/in/yonatantal",
        facebookURL: "https://facebook.com/yonatan.tal",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Loves mentoring new developers.",
        jobs_history: [
            {
                role: "Frontend Developer",
                companyName: "GreenWave",
                startDate: "2010-08-02",
                endDate: "Present",
            },
            {
                role: "Backend Developer",
                companyName: "StartupLabs",
                startDate: "2013-10-20",
                endDate: "2016-06-15",
            },
        ],
        years_of_experience: 8,
        groups: [
            "Business Development",
            "Public Relations",
            "Administration",
            "Security",
        ],
    },
    {
        fullName: "Hila Shamir",
        email: "hila.shamir@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/45.jpg",
        location: {
            country: "Israel",
            state: "Jerusalem District",
            city: "Ma'ale Adumim",
        },
        phone: "+972-55-726-2125",
        linkedinURL: "https://linkedin.com/in/hilashamir",
        facebookURL: "https://facebook.com/hila.shamir",
        wantsUpdates: false,
        gender: "Non-binary",
        additionalInfo: "Focuses on cybersecurity and data privacy.",
        jobs_history: [
            {
                role: "Fullstack Engineer",
                companyName: "Designify",
                startDate: "2011-03-11",
                endDate: "Present",
            },
        ],
        years_of_experience: 13,
        groups: ["QA / Testing", "Sales", "Human Resources"],
    },
    {
        fullName: "Boaz Regev",
        email: "boaz.regev@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/46.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Haifa",
        },
        phone: "+972-53-672-5970",
        linkedinURL: "https://linkedin.com/in/boazregev",
        facebookURL: "https://facebook.com/boaz.regev",
        wantsUpdates: true,
        gender: "Non-binary",
        additionalInfo: "Interested in sustainable tech solutions.",
        jobs_history: [
            {
                role: "Marketing Coordinator",
                companyName: "NextGen",
                startDate: "2022-03-16",
                endDate: "Present",
            },
        ],
        years_of_experience: 8,
        groups: ["Business Development", "Finance", "Sales"],
    },
    {
        fullName: "Hila Elbaz",
        email: "hila.elbaz@example.com",
        profile_img: "https://randomuser.me/api/portraits/women/47.jpg",
        location: {
            country: "Israel",
            state: "Central District",
            city: "Rishon LeZion",
        },
        phone: "+972-54-791-8699",
        linkedinURL: "https://linkedin.com/in/hilaelbaz",
        facebookURL: "https://facebook.com/hila.elbaz",
        wantsUpdates: false,
        gender: "Female",
        additionalInfo: "Focuses on cybersecurity and data privacy.",
        jobs_history: [
            {
                role: "Support Specialist",
                companyName: "InsightData",
                startDate: "2013-10-02",
                endDate: "Present",
            },
        ],
        years_of_experience: 8,
        groups: ["Operations", "QA / Testing"],
    },
    {
        fullName: "Itai Goldman",
        email: "itai.goldman@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/48.jpg",
        location: {
            country: "Israel",
            state: "Northern District",
            city: "Nazareth",
        },
        phone: "+972-54-161-1996",
        linkedinURL: "https://linkedin.com/in/itaigoldman",
        facebookURL: "https://facebook.com/itai.goldman",
        wantsUpdates: false,
        gender: "Male",
        additionalInfo: "Passionate about user research and accessibility.",
        jobs_history: [
            {
                role: "Intern",
                companyName: "QuantumSoft",
                startDate: "2015-01-13",
                endDate: "Present",
            },
        ],
        years_of_experience: 7,
        groups: [
            "UX Research",
            "Business Development",
            "Customer Success",
            "IT",
            "Sales",
        ],
    },
    {
        fullName: "Dafna Oren",
        email: "dafna.oren@example.com",
        profile_img: "https://randomuser.me/api/portraits/men/49.jpg",
        location: {
            country: "Israel",
            state: "Haifa District",
            city: "Haifa",
        },
        phone: "+972-54-532-1167",
        linkedinURL: "https://linkedin.com/in/dafnaoren",
        facebookURL: "https://facebook.com/dafna.oren",
        wantsUpdates: true,
        gender: "Non-binary",
        additionalInfo: "Interested in AI and machine learning advancements.",
        jobs_history: [
            {
                role: "Fullstack Engineer",
                companyName: "InnoTech",
                startDate: "2019-09-24",
                endDate: "Present",
            },
        ],
        years_of_experience: 11,
        groups: ["Human Resources", "Training", "Legal"],
    },
];

module.exports = { members };
